# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = "Fastly Compute starter kit for JavaScript, demonstrating webpack for bundling。"
language = "javascript"
manifest_version = 3
name = "Default starter for JavaScript"

[scripts]
build = "npm run build"
post_init = "npm install"
